wget https://www.kellogg.northwestern.edu/images/students/all/mob354.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/akb9553.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mse734.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/tcb441.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/tcs364.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/trd853.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/zjf178.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mgs454.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jpg123.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mjg198.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/xhr193.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/ajm205.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mjk9811.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mlk063.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rly4607.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jvl381.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/bll079.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rpl532.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rel229.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/kmm7245.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/kmr700.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/gco5932.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/npp2274.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/apt1023.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/ser445.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mrv002.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/brl953.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/vss834.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/css991.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/pss299.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jas298.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rku252.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/sva291.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jgw967.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mwf698.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jmw343.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mwr899.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/eyb744.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mdz325.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/szh334.jpg